services:
  nfsv2-server:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: nfsv2-vxworks-debian
    privileged: true
    network_mode: host
    volumes:
      - ./vxworks-files:/nfs/vxworks
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - TZ=America/New_York

