services:
  nfsv2-server:
    build: .
    container_name: nfsv2-vxworks
    privileged: true
    network_mode: host
    volumes:
      - ./vxworks-files:/nfs/vxworks
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
      - NET_ADMIN
    environment:
      - TZ=America/New_York

